<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXsB4oIz\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXsB4oIz/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXsB4oIz.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXsB4oIz\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXsB4oIz\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XsB4oIz',
    'container.build_id' => 'f0fe4df9',
    'container.build_time' => 1652182440,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXsB4oIz');
